Repository techsupport101/sus-prog, pull requests merged in 2024-12, with the labels that each got.

#3 Added Lady Brown mech code
  src/main.cpp
Labels: enhancement, driver, competition

#7 Made changes to templates due to oversights
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue-report.md
Labels: bug

#6 Patch-3
  README.md
  blockCode/CustomTeamBlueTeam.v5blocks
  blockCode/CustomTeamBlueTeamText.v5cpp
  src/main.cpp
Labels: bug, enhancement
